#!/bin/bash

src="./internal/css/*.css"
dst="./static/css/style.css"

if test -f $dst; then
    rm -f $dst
fi

(
    echo "/*  **************************************************************************"
    echo "        DO NOT EDIT - GENERATED BY $0"
    echo "**  *************************************************************************/"
) >>$dst

for f in $src; do
    (
        echo
        echo
        echo
        echo "/*  **************************************************************************"
        echo "        $(basename $f)"
        echo "**  *************************************************************************/"
        echo
        cat "$f"
    ) >>$dst
done
